<?php
declare(strict_types=1);
require_once __DIR__.'/includes/init.php';
require_login();
$errors=[]; $success=null;
$cart=cart_items();
if(!$cart) redirect('cart.php');
$ids=implode(',',array_map('intval',array_keys($cart)));
$items=db_all("SELECT v.id variant_id,v.size,v.color,v.sku,v.stock,p.id product_id,p.name,p.price,p.sale_price FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.id IN ($ids) AND p.is_active=1");
$subtotal=0; foreach($items as &$item){$item['quantity']=(int)$cart[$item['variant_id']]; if($item['quantity']<1||$item['quantity']>(int)$item['stock'])$errors[]=$item['name'].' is no longer available in that quantity.'; $item['unit_price']=effective_price($item); $item['line_total']=$item['unit_price']*$item['quantity']; $subtotal+=$item['line_total'];} unset($item);
if(count($items)!==count($cart))$errors[]='One or more cart items are no longer available.';
$shipping=$subtotal>=3000?0:150; $total=$subtotal+$shipping;
if(is_post()){
 require_csrf();
 $name=input_str('customer_name',120);$email=strtolower(input_str('email',190));$phone=input_str('phone',30);$address=input_str('address_line',255);$city=input_str('city',80);$state=input_str('state',80);$postal=input_str('postal_code',20);
 if($name===''||$phone===''||$address===''||$city===''||$state===''||$postal==='')$errors[]='Please complete all delivery details.';
 if(!is_valid_email($email))$errors[]='Please enter a valid email address.';
 if(!$errors){$pdo=db();try{$pdo->beginTransaction(); foreach($items as $item){$locked=db_one('SELECT stock FROM product_variants WHERE id=? FOR UPDATE',[(int)$item['variant_id']]);if(!$locked||$item['quantity']>(int)$locked['stock'])throw new RuntimeException('Stock changed. Please review your cart.');}
 db_query('INSERT INTO orders(user_id,customer_name,email,phone,address_line,city,state,country,postal_code,subtotal,shipping,total,payment_method) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[(int)$_SESSION['user_id'],$name,$email,$phone,$address,$city,$state,'Nepal',$postal,$subtotal,$shipping,$total,'cod']);$orderId=(int)$pdo->lastInsertId();$number=make_order_number($orderId);db_query('UPDATE orders SET order_number=? WHERE id=?',[$number,$orderId]);foreach($items as $item){db_query('INSERT INTO order_items(order_id,product_id,variant_id,product_name,sku,size,color,unit_price,quantity,line_total) VALUES(?,?,?,?,?,?,?,?,?,?)',[$orderId,$item['product_id'],$item['variant_id'],$item['name'],$item['sku'],$item['size'],$item['color'],$item['unit_price'],$item['quantity'],$item['line_total']]);db_query('UPDATE product_variants SET stock=stock-? WHERE id=?',[$item['quantity'],$item['variant_id']]);}db_query('DELETE FROM cart WHERE user_id=?',[(int)$_SESSION['user_id']]);$pdo->commit();$_SESSION['cart']=[];$success=$number;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to place your order. Please try again.';}}
}
$pageTitle='Checkout';require __DIR__.'/includes/header.php'; ?><main class="container page-section"><p class="eyebrow">Secure checkout</p><h1>Complete your order</h1><?php if($success): ?><div class="alert alert-success"><h2>Order confirmed</h2><p>Thank you. Your order number is <strong><?=e($success)?></strong>.</p><a class="btn btn-primary" href="<?=e(url('account.php'))?>">View my orders</a></div><?php else: ?><?php foreach($errors as $error): ?><div class="alert alert-error"><?=e($error)?></div><?php endforeach; ?><div class="checkout-layout"><form method="post" class="form-stack"><?=csrf_field()?><label>Full name<input name="customer_name" required value="<?=e(current_user()['first_name'].' '.current_user()['last_name'])?>"></label><label>Email<input type="email" name="email" required value="<?=e(current_user()['email'])?>"></label><label>Phone<input name="phone" required value="<?=e(current_user()['phone']??'')?>"></label><label>Address<input name="address_line" required></label><div class="form-grid"><label>City<input name="city" required></label><label>Province<input name="state" required></label></div><label>Postal code<input name="postal_code" required></label><p>Payment: <strong>Cash on delivery</strong></p><button class="btn btn-primary btn-block" type="submit">Place order · <?=e(money($total))?></button></form><aside class="cart-summary"><h2>Order summary</h2><?php foreach($items as $item): ?><p><?=e($item['name'])?> × <?=e($item['quantity'])?><br><strong><?=e(money($item['line_total']))?></strong></p><?php endforeach; ?><hr><p>Subtotal <strong><?=e(money($subtotal))?></strong></p><p>Shipping <strong><?=e($shipping?money($shipping):'Free')?></strong></p><p>Total <strong><?=e(money($total))?></strong></p></aside></div><?php endif; ?></main><?php require __DIR__.'/includes/footer.php'; ?>
