<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/admin-auth.php';
$stats = [
 'sales' => (float)(db_value("SELECT COALESCE(SUM(total),0) FROM orders WHERE status NOT IN ('cancelled')") ?? 0),
 'orders' => (int)(db_value('SELECT COUNT(*) FROM orders') ?? 0),
 'pending' => (int)(db_value("SELECT COUNT(*) FROM orders WHERE status IN ('pending','confirmed','processing')") ?? 0),
 'products' => (int)(db_value('SELECT COUNT(*) FROM products WHERE is_active=1') ?? 0),
 'customers' => (int)(db_value('SELECT COUNT(*) FROM users WHERE is_active=1') ?? 0),
];
$recent = db_all('SELECT order_number, customer_name, total, status, created_at FROM orders ORDER BY created_at DESC LIMIT 8');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | <?= e(APP_NAME) ?></title><link rel="stylesheet" href="<?= e(asset('css/style.css')) ?>"><style>.admin-shell{max-width:1240px;margin:auto;padding:2rem}.admin-nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:2rem}.admin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;margin-bottom:2rem}.admin-card{border:1px solid #ddd;border-radius:12px;padding:1.25rem;background:#fff}.admin-card small{display:block;color:#777}.admin-card strong{font-size:1.7rem}.admin-table{width:100%;border-collapse:collapse;background:#fff}.admin-table th,.admin-table td{text-align:left;padding:.8rem;border-bottom:1px solid #eee}.admin-table th{font-size:.8rem;text-transform:uppercase;color:#777}.admin-actions{display:flex;gap:.75rem;flex-wrap:wrap}</style></head><body><main class="admin-shell"><header class="admin-nav"><div><a class="logo" href="<?= e(url()) ?>">BFM</a><p>Store dashboard</p></div><div class="admin-actions"><a class="btn" href="<?= e(url('shop.php')) ?>">View store</a><a class="btn" href="<?= e(url('admin/logout.php')) ?>">Log out</a></div></header><section class="admin-grid" aria-label="Store statistics"><article class="admin-card"><small>Revenue</small><strong><?= e(money($stats['sales'])) ?></strong></article><article class="admin-card"><small>Total orders</small><strong><?= e($stats['orders']) ?></strong></article><article class="admin-card"><small>Open orders</small><strong><?= e($stats['pending']) ?></strong></article><article class="admin-card"><small>Products</small><strong><?= e($stats['products']) ?></strong></article><article class="admin-card"><small>Customers</small><strong><?= e($stats['customers']) ?></strong></article></section><section><h2>Recent orders</h2><?php if (!$recent): ?><p>No orders yet.</p><?php else: ?><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach ($recent as $order): ?><tr><td><?= e($order['order_number'] ?: '#'.$order['id']) ?></td><td><?= e($order['customer_name']) ?></td><td><?= e(money($order['total'])) ?></td><td><?= e(ucfirst($order['status'])) ?></td><td><?= e(format_date($order['created_at'])) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></main></body></html>
